name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./cmd/kcvm/
    
    - name: ls pwd
      run: ls -la

    - name: Create a Release
      uses: actions/create-release@v1.1.4
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: ${{ github.sha }}
        # The name of the release. For example, `Release v1.0.1`
        release_name: Release ${{ github.sha }}
        prerelease:: true


